# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install-packages:
    docker:
      - image: circleci/node:8.12.0-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

  build:
    docker:
      - image: circleci/node:8.12.0-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn build

  lint:
    docker:
      - image: circleci/node:8.12.0-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint

  stylelint:
    docker:
      - image: circleci/node:8.12.0-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn stylelint

  test:
    docker:
      - image: circleci/node:8.12.0-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test --watch=false --code-coverage
      - store_artifacts:
          path: coverage

  e2e:
    docker:
      - image: circleci/node:8.12.0-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - install-packages
      - build:
          requires:
            - install-packages
      - lint:
          requires:
            - build
      - stylelint:
          requires:
            - build
      - test:
          requires:
            - build
      - e2e:
          requires:
            - build
